--------------------------------------------------------
-- Archivo creado  - jueves-octubre-31-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AMIGOS
--------------------------------------------------------

  CREATE TABLE "SIM24BNUPA"."AMIGOS" 
   (	"AMIGO_CON" VARCHAR2(20 BYTE), 
	"AMIGO_DE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Table HOTEL
--------------------------------------------------------

  CREATE TABLE "SIM24BNUPA"."HOTEL" 
   (	"CODIGO" VARCHAR2(20 BYTE), 
	"ESTRELLAS" NUMBER, 
	"WIFI_GRATIS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Table OPINION
--------------------------------------------------------

  CREATE TABLE "SIM24BNUPA"."OPINION" 
   (	"FECHA" DATE, 
	"COMENTARIO" VARCHAR2(200 BYTE), 
	"PUNTUACION" NUMBER, 
	"RESPUESTA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Table RESTAURANTE
--------------------------------------------------------

  CREATE TABLE "SIM24BNUPA"."RESTAURANTE" 
   (	"TIPO_COMIDA" VARCHAR2(20 BYTE), 
	"CODIGO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Table SITIO
--------------------------------------------------------

  CREATE TABLE "SIM24BNUPA"."SITIO" 
   (	"NOMBRE" VARCHAR2(40 BYTE), 
	"DIRECCION" VARCHAR2(40 BYTE), 
	"POBLACION" VARCHAR2(40 BYTE), 
	"TELEFONO" VARCHAR2(10 BYTE), 
	"ESTRELLAS" NUMBER, 
	"WIFIGRATIS" VARCHAR2(2 BYTE), 
	"CODIGO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "SIM24BNUPA"."USUARIO" 
   (	"CORREO" VARCHAR2(40 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDOS" VARCHAR2(40 BYTE), 
	"CONOCEA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
REM INSERTING into SIM24BNUPA.AMIGOS
SET DEFINE OFF;
REM INSERTING into SIM24BNUPA.HOTEL
SET DEFINE OFF;
REM INSERTING into SIM24BNUPA.OPINION
SET DEFINE OFF;
Insert into SIM24BNUPA.OPINION (FECHA,COMENTARIO,PUNTUACION,RESPUESTA) values (to_date('27/10/24','DD/MM/RR'),'Chinches muy gorditas','3',null);
Insert into SIM24BNUPA.OPINION (FECHA,COMENTARIO,PUNTUACION,RESPUESTA) values (to_date('27/10/24','DD/MM/RR'),'Chinches muy saludables','4',null);
REM INSERTING into SIM24BNUPA.RESTAURANTE
SET DEFINE OFF;
REM INSERTING into SIM24BNUPA.SITIO
SET DEFINE OFF;
Insert into SIM24BNUPA.SITIO (NOMBRE,DIRECCION,POBLACION,TELEFONO,ESTRELLAS,WIFIGRATIS,CODIGO) values ('La Chinche alegre','C. Pulgas 2','Alcafran','999666999','1','NO','111');
Insert into SIM24BNUPA.SITIO (NOMBRE,DIRECCION,POBLACION,TELEFONO,ESTRELLAS,WIFIGRATIS,CODIGO) values ('La Cucaracha Feliz','C. Pulgas 5','Alcafran','999666777','0','NO','222');
Insert into SIM24BNUPA.SITIO (NOMBRE,DIRECCION,POBLACION,TELEFONO,ESTRELLAS,WIFIGRATIS,CODIGO) values ('La Chinche Cochina','C. Gaurrete 8','Gotham','999654777','2','No','333');
REM INSERTING into SIM24BNUPA.USUARIO
SET DEFINE OFF;
Insert into SIM24BNUPA.USUARIO (CORREO,NOMBRE,APELLIDOS,CONOCEA) values ('lola@uncorreo.es','Lola','Mento','Victor');
Insert into SIM24BNUPA.USUARIO (CORREO,NOMBRE,APELLIDOS,CONOCEA) values ('cardo@sucorreo.es','Ricardo','Borriquero','Lola');
Insert into SIM24BNUPA.USUARIO (CORREO,NOMBRE,APELLIDOS,CONOCEA) values ('aitor@sucorreo.es','Aitor','Tilla','Lola');
Insert into SIM24BNUPA.USUARIO (CORREO,NOMBRE,APELLIDOS,CONOCEA) values ('alan@sucorreo.es','Alan','Brito','Lola');
--------------------------------------------------------
--  DDL for Index AMIGOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIM24BNUPA"."AMIGOS_PK" ON "SIM24BNUPA"."AMIGOS" ("AMIGO_CON", "AMIGO_DE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index HOTEL_CODIGO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIM24BNUPA"."HOTEL_CODIGO_PK" ON "SIM24BNUPA"."HOTEL" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index RESTAURANTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIM24BNUPA"."RESTAURANTE_PK" ON "SIM24BNUPA"."RESTAURANTE" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index SITIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIM24BNUPA"."SITIO_PK" ON "SIM24BNUPA"."SITIO" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027930
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIM24BNUPA"."SYS_C0027930" ON "SIM24BNUPA"."USUARIO" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIM24BNUPA"."USUARIO_PK" ON "SIM24BNUPA"."USUARIO" ("CORREO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS" ;
--------------------------------------------------------
--  Constraints for Table AMIGOS
--------------------------------------------------------

  ALTER TABLE "SIM24BNUPA"."AMIGOS" MODIFY ("AMIGO_CON" NOT NULL ENABLE);
  ALTER TABLE "SIM24BNUPA"."AMIGOS" MODIFY ("AMIGO_DE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HOTEL
--------------------------------------------------------

  ALTER TABLE "SIM24BNUPA"."HOTEL" ADD CONSTRAINT "HOTEL_CODIGO_PK" PRIMARY KEY ("CODIGO")
  USING INDEX "SIM24BNUPA"."HOTEL_CODIGO_PK"  ENABLE;
  ALTER TABLE "SIM24BNUPA"."HOTEL" ADD CONSTRAINT "HOTEL_ESTRELLAS_CHK" CHECK (ESTRELLAS BETWEEN 1 AND 5) ENABLE;
  ALTER TABLE "SIM24BNUPA"."HOTEL" ADD CONSTRAINT "HOTEL_WIFI_GRATIS_CHK" CHECK (WIFI_GRATIS IN ('SI', 'NO')) ENABLE;
  ALTER TABLE "SIM24BNUPA"."HOTEL" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OPINION
--------------------------------------------------------

  ALTER TABLE "SIM24BNUPA"."OPINION" MODIFY ("FECHA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESTAURANTE
--------------------------------------------------------

  ALTER TABLE "SIM24BNUPA"."RESTAURANTE" ADD CONSTRAINT "RESTAURANTE_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TS_ALUMNOS"  ENABLE;
  ALTER TABLE "SIM24BNUPA"."RESTAURANTE" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SITIO
--------------------------------------------------------

  ALTER TABLE "SIM24BNUPA"."SITIO" ADD CONSTRAINT "SITIO_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"  ENABLE;
  ALTER TABLE "SIM24BNUPA"."SITIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SIM24BNUPA"."SITIO" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "SIM24BNUPA"."SITIO" MODIFY ("POBLACION" NOT NULL ENABLE);
  ALTER TABLE "SIM24BNUPA"."SITIO" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "SIM24BNUPA"."SITIO" MODIFY ("WIFIGRATIS" NOT NULL ENABLE);
  ALTER TABLE "SIM24BNUPA"."SITIO" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "SIM24BNUPA"."USUARIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SIM24BNUPA"."USUARIO" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "SIM24BNUPA"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("CORREO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_ALUMNOS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AMIGOS
--------------------------------------------------------

  ALTER TABLE "SIM24BNUPA"."AMIGOS" ADD CONSTRAINT "AMIGOS_CON_USUARIO_FK" FOREIGN KEY ("AMIGO_CON")
	  REFERENCES "SIM24BNUPA"."USUARIO" ("CORREO") ENABLE;
  ALTER TABLE "SIM24BNUPA"."AMIGOS" ADD CONSTRAINT "AMIGOS_DE_USUARIO_FK" FOREIGN KEY ("AMIGO_DE")
	  REFERENCES "SIM24BNUPA"."USUARIO" ("CORREO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HOTEL
--------------------------------------------------------

  ALTER TABLE "SIM24BNUPA"."HOTEL" ADD CONSTRAINT "HOTEL_SITIO_FK" FOREIGN KEY ("CODIGO")
	  REFERENCES "SIM24BNUPA"."SITIO" ("CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESTAURANTE
--------------------------------------------------------

  ALTER TABLE "SIM24BNUPA"."RESTAURANTE" ADD CONSTRAINT "RESTAURANTE_CODIGO_FK" FOREIGN KEY ("CODIGO")
	  REFERENCES "SIM24BNUPA"."SITIO" ("CODIGO") ENABLE;
